name: Backport

on:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  backport:
    uses: neteye-platform/repo-commons/.github/workflows/backport.yaml@4e30dd80d90a03104198b5fe0b9d93664b4d3c53 # main
    secrets: inherit
